AWSTemplateFormatVersion: 2010-09-09
Description: Frontend Template
Resources:
  SessionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: mongocloud_sessions
      KeySchema:
        - AttributeName: sessionId
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: sessionId
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: mongocloud_users
      KeySchema:
        - AttributeName: customerId
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: customerId
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  InstancesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: mongocloud_instances
      KeySchema:
        - AttributeName: instanceId
          KeyType: HASH
        - AttributeName: customerId
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: instanceId
          AttributeType: S
        - AttributeName: customerId
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
       
