AWSTemplateFormatVersion: 2010-09-09
Description: Frontend Template
Resources:
  SessionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: mongocloud_sessions
      KeySchema:
        - AttributeName: sessionId
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: sessionId
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
